all: false
log-level: info
dir: "{{.InterfaceDir}}"
structname: "Mock{{.InterfaceName}}"
filename: "{{.InterfaceFile | replaceAll \".go\" \"_mock.go\"}}"
pkgname: "{{.SrcPackageName}}"
packages:
  github.com/aws/aws-sdk-go/service/s3/s3iface:
    config:
      dir: "common/archiver/s3store/mocks"
      filename: "s3_api_mock.go"
      structname: "{{.InterfaceName}}"
      pkgname: "mocks"
    interfaces:
      S3API:
  github.com/uber/cadence/common/blobstore:
    interfaces:
      Client: