// Code generated by tmpl. DO NOT EDIT.
//
// go-generate command: tmpl persistencetask -type ActivityTask
// in file: dataManagerInterfaces.go:54

package persistence

import "time"

// GetType returns the type of the task
func (t *ActivityTask) GetType() int {
	return TransferTaskTypeActivityTask
}

// GetVersion returns the version of the task
func (t *ActivityTask) GetVersion() int64 {
	return t.Version
}

// SetVersion returns the version of the task
func (t *ActivityTask) SetVersion(version int64) {
	t.Version = version
}

// GetTaskID returns the sequence ID of the task
func (t *ActivityTask) GetTaskID() int64 {
	return t.TaskID
}

// SetTaskID sets the sequence ID of the task
func (t *ActivityTask) SetTaskID(id int64) {
	t.TaskID = id
}

// GetVisibilityTimestamp gets the visibility timestamp of the task
func (t *ActivityTask) GetVisibilityTimestamp() time.Time {
	return t.VisibilityTimestamp
}

// SetVisibilityTimestamp sets the visibility timestamp of the task
func (t *ActivityTask) SetVisibilityTimestamp(timestamp time.Time) {
	t.VisibilityTimestamp = timestamp
}
